### ISSUE TITLE
bug: Undocumented dependency on pdftotext provided by poppler-utils

### ISSUE THREAD

**Issue by blairw** [CoLRev-Ecosystem/colrev#126]
# Bug Report: Undocumented dependency on pdftotext provided by poppler-utils

**colrev version:**

`colrev version 0.7.0` (installed through pip)

Running in Ubuntu on WSL:

```
neofetch -off

OS: Ubuntu 22.04.1 LTS on Windows 10 x86_64
Kernel: 5.15.79.1-microsoft-standard-WSL2
Uptime: 7 hours, 7 mins 
Packages: 1018 (dpkg) 
Shell: zsh 5.8.1 
Theme: Adwaita [GTK3] 
Icons: Adwaita [GTK3] 
Terminal: /dev/pts/4 
CPU: Intel i7-8650U (8) @ 2.111GHz 
GPU: 1319:00:00.0 Microsoft Corporation Device 008e 
Memory: 2861MiB / 15925MiB
```

**Current behavior:**

Running `colrev pdfs` fails because `poppler-utils` is not installed to provide `/usr/bin/pdftotext`. See Traceback provided later in this report below.

Problem is resolved if the user manually installs `poppler-utils`, e.g. on Ubuntu:

```
sudo apt-get install poppler-utils
```

**Expected behavior:**

Running `colrev pdfs` completes successfully.

**Steps to reproduce:**

Go through the usual colrev workflow up to `colrev pdfs` and then attempt to run `colrev pdfs`

**Related code:**

Traceback below.

```
2023-02-19 20:37:16 [INFO] Prep PDFs
2023-02-19 20:37:16 [INFO] Prepare PDFs, validating them against their metadata, removing additional pages, ensuring machine readability.
2023-02-19 20:37:16 [INFO] INFO: This operation is computationally intensive and may take longer.
2023-02-19 20:37:16 [INFO] PDFs to prep                          6 PDFs
2023-02-19 20:37:20 [INFO]  Hannonen2020                            pdf_imported → pdf_needs_manual_preparation (validate_completeness)
Traceback (most recent call last):
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/bin/colrev", line 8, in <module>
    sys.exit(main())
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/lib/python3.10/site-packages/colrev/ui_cli/cli.py", line 1054, in pdfs
    pdf_prep_operation.main(batch_size=0)
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/lib/python3.10/site-packages/colrev/ops/pdf_prep.py", line 405, in main
    pdf_prep_record_list = pool.map(self.prepare_pdf, pdf_prep_data["items"])
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/lib/python3.10/site-packages/colrev/ops/pdf_prep.py", line 156, in prepare_pdf
    record.data = endpoint.prep_pdf(self, record, pad)  # type: ignore
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 92, in new_function
    return timeout_wrapper(*args, **kwargs)
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 152, in __call__
    return self.value
  File "/home/blair/00blair-wsl/gitrepos-colrev/colrev-repos-venv/lib/python3.10/site-packages/timeout_decorator/timeout_decorator.py", line 175, in value
    raise load
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pdftotext'
```

**Other information:**

Suggestions on how to fix:

- Maybe the documentation (https://colrev.readthedocs.io/) or pypi page (https://pypi.org/project/colrev/0.7.0/) could state poppler-utils as a requirement? (e.g., in addition to Git and Docker which are stated already)
- Alternatively/additionally, perhaps the colrev codebase itself could check if `/usr/bin/pdftotext` exists, and if not, provide a gentle message suggesting the user should install it (essentially a friendly version of what the final line of the Traceback already implies). 😄

**Comment by geritwagner** [comment]
Thank you for reporting this issue. We could even think about using `PdfFileReader.getPage(i).extractText()` per default. The poppler/pdftotext seems to be slightly more reliable. But we could simply use it as a backup (if the extractText() fails) and print a notification if pdftotext is not available (instead of raising an Exception).
