### ISSUE TITLE
bug: colrev data --add colrev_built_in.prisma crashes on TypeError

### ISSUE THREAD

**Issue by blairw** [CoLRev-Ecosystem/colrev#133]
# Bug Report

**colrev version:**

Tested in `0.7.0` and in https://github.com/CoLRev-Ecosystem/colrev/commit/e18459fe5ca3e703817316ce6d6810844d05dbe5

**Current behavior:**

Running `colrev data --add colrev_built_in.prisma` crashes and corrupts `settings.json`

**Expected behavior:**

Running `colrev data --add colrev_built_in.prisma` sets up a nice PRISMA diagram

**Steps to reproduce:**

Run `colrev data --add colrev_built_in.prisma`

**Related code:**

```
colrev data --add colrev_built_in.prisma
2023-03-07 13:28:21 [INFO] Add colrev_built_in.prisma data endpoint
Traceback (most recent call last):
  File "/home/blair/00blair-wsl/gitrepos-colrev/.venv_colrev_git/bin/colrev", line 8, in <module>
    sys.exit(main())
  File "/home/blair/00blair-wsl/gitrepos-colrev/.venv_colrev_git/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/blair/00blair-wsl/gitrepos-colrev/.venv_colrev_git/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/blair/00blair-wsl/gitrepos-colrev/.venv_colrev_git/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/blair/00blair-wsl/gitrepos-colrev/.venv_colrev_git/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/blair/00blair-wsl/gitrepos-colrev/.venv_colrev_git/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/blair/00blair-wsl/gitrepos-colrev/.venv_colrev_git/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/blair/00blair-wsl/gitrepos-colrev/.venv_colrev_git/lib/python3.10/site-packages/colrev/ui_cli/cli.py", line 1634, in data
    colrev.ui_cli.add_packages.add_data(
  File "/home/blair/00blair-wsl/gitrepos-colrev/.venv_colrev_git/lib/python3.10/site-packages/colrev/ui_cli/add_packages.py", line 190, in add_data
    data_operation.add_data_endpoint(data_endpoint=default_endpoint_conf)
  File "/home/blair/00blair-wsl/gitrepos-colrev/.venv_colrev_git/lib/python3.10/site-packages/colrev/ops/data.py", line 201, in add_data_endpoint
    self.review_manager.save_settings()
  File "/home/blair/00blair-wsl/gitrepos-colrev/.venv_colrev_git/lib/python3.10/site-packages/colrev/review_manager.py", line 153, in save_settings
    colrev.settings.save_settings(review_manager=self)
  File "/home/blair/00blair-wsl/gitrepos-colrev/.venv_colrev_git/lib/python3.10/site-packages/colrev/settings.py", line 694, in save_settings
    json.dump(exported_dict, outfile, indent=4)
  File "/usr/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
```

**Other information:**

This seems to happen because `custom_asdict_factory(...)` in `utils.py` does not process the list of `PosixPath` objects in `diagram_path` for the PRISMA configuration portion of `settings.json`.

Placing the following hacky code in `save_settings(...)` in `settings.py` - immediately after `exported_dict = asdict(...)` - seems to be a working workaround, albeit very ugly:

```python
xi = 0
for x in exported_dict["data"]["data_package_endpoints"]:
    if x["endpoint"] == "colrev_built_in.prisma":
        yi = 0
        for y in exported_dict["data"]["data_package_endpoints"][xi]["diagram_path"]:
            exported_dict["data"]["data_package_endpoints"][xi]["diagram_path"][yi] = str(y)
            yi += 1
    xi += 1
```

**Comment by geritwagner** [comment]
Thank you for catching this. I have suggested a modification of the custom_asdict_factory. Does that resolve the bug?
